---
- name: include rocky_repos.yml
  include_tasks: rocky_repos.yml
  when: ansible_distribution == 'Rocky'

- name: include ubuntu_repos.yml
  include_tasks: ubuntu_repos.yml
  when: ansible_distribution == 'Ubuntu'

- name: include rocky_packages.yml
  include_tasks: rocky_packages.yml
  when: ansible_distribution == 'Rocky'

- name: include ubuntu_packages.yml
  include_tasks: ubuntu_packages.yml
  when: ansible_distribution == 'Ubuntu'