---
- name: install mariadb on ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_mariadb_packages }}"
  when: ansible_distribution == 'Ubuntu'

- name: install apache2 packages on ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_apache2_packages }}"
  when: ansible_distribution == 'Ubuntu'

- name: install PHP packages on ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_php_packages }}"
  when: ansible_distribution == 'Ubuntu'