---
- name: install PHP packages on ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_php_packages }}"
  when: ansible_distribution == 'Ubuntu'

- name: install PHP packages on rocky
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ rocky_php_packages }}"
  when: ansible_distribution == 'Rocky'

- name: set php memory_limit to 1024M on ubuntu
  replace:
    path: /etc/php/8.2/fpm/php.ini
    regexp: '128M'
    replace: '1024M'
  when: ansible_distribution == 'Ubuntu'

- name: set php memory_limit to 1024M on rocky
  replace:
    path: /etc/opt/remi/php82/php.ini
    regexp: '128M'
    replace: '1024M'
  when: ansible_distribution == 'Rocky'

