---
- name: open http port
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled

- name: open https port
  ansible.posix.firewalld:
    service: https
    permanent: true
    state: enabled
