---
- name: install apache2 on ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_packages }}"
  when: ansible_distribution == 'Ubuntu'

- name: install httpd on rocky
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ rocky_packages }}"
  when: ansible_distribution == 'Rocky'